### ISSUE TITLE
How to group OpenStack Resources into Ansible Groups?

### ISSUE THREAD

**Issue by afritzler** [CiscoCloud/terraform.py#20]
In #13 it is shown how AWS resouces can be grouped into ansible groups. How can this be accoplished for OpenStack instances? I tried to add a `role` attribute within the `metadata` block, but this does not seem to be working. Any ideas?

Thanks!

**Comment by stevendborrelli** [comment]
@afritzler here is an example we use in mantl:
```
 metadata              = {
                            dc = "${var.datacenter}"
                            role = "control"
                            ssh_user = "${ var.ssh_user }"
                          }
```
https://github.com/CiscoCloud/microservices-infrastructure/blob/master/terraform/openstack/hosts-floating/main.tf#L49

Then in the yml file for ansible we have a block like the following:
```
- hosts: role=control
  gather_facts: no
  vars:
    consul_dns_domain: consul
    consul_servers_group: role=control
    mesos_leaders_group: role=control
    mesos_mode: leader
    zookeeper_server_group: role=control
  roles:
    - vault
    - zookeeper
    - mesos

```
